Seqsampling
Pyomo/mpi-sppy pull request #122
Opened 2021-05-21 12:11 UTC by sylvainczx

Sequential sampling procedures to compute confidence intervals.

2021-05-21 13:48 UTC, DLWoodruff commented on doc/src/confidence_intervals.rst
> +.. Confidence intervals:
Anchors need a leading underscore

2021-05-21 13:54 UTC, DLWoodruff commented on mpisppy/confidence_intervals/seqsampling.py
> +    path: str
Probably, this function should return xhat and not write it to a file

2021-05-26 22:19 UTC, bknueven requested changes
Need to fix issue with Xhat_Eval spoke friend classes

2021-05-26 22:19 UTC, bknueven commented on mpisppy/utils/xhat_eval.py
> +        self._create_solvers()
The classes derived from `Xhat_Eval` probably also do this somewhere. We should eliminate the associated calls in the derived classes to ensure we're not doing extra work.

2021-05-26 22:35 UTC, bknueven approved these changes
I fixed the issue I had

2021-05-26 22:38 UTC, merged